[[params.links.developer]]
  name = "More info"
  url = "mailto:info@openva.net"
  icon = "fa-solid fa-circle-info"
  desc = "Know more about VA algorithms or our team"
[[params.links.developer]]
  name = "Help desk"
  url = "mailto:help@openva.net"
  icon = "fa-solid fa-question"
  desc = "Ask for help"
[[params.links.developer]]
  name = "Issues reporting"
  url = "https://github.com/verbal-autopsy-software/openVA/issues"
  icon = "fab fa-github"
  desc = "Reporting issues with software"